### ISSUE TITLE
About description

### ISSUE THREAD

**Issue by silverpill** [YunoHost-Apps/mitra_ynh#21]
https://apps.yunohost.org/app/mitra

>Your server will be compatible with Mastodon, Pleroma, Pixelfed, Friendica, Hubzilla, (streams), Funkwhale, Peertube, Plume, WriteFreely and many, many more.

Mitra is compatible with all those services except Funkwhale

>This app is only compatible with these specific architectures: amd64 

What other architectures YunoHost supports? I think Mitra should be able to run on non-amd64 machines too.

**Comment by dragondaddy** [comment]
> Mitra is compatible with all those services except Funkwhale

👍 I'll remove it in the next update

> What other architectures YunoHost supports? 

arm64, i386, arm64 and armhf. I also think it should run fine on other archs, it's just that I don't have the hardware to test it. Anyhow, I'll probably change for "all" also in the next update.

**Comment by silverpill** [comment]
I don't have hard data on those archs, but at least Rust backend should compile without issues. Let's find out :)

**Comment by silverpill** [comment]
Thanks!
